"""adapter.py — Deterministic adaptor: cad_ir_v0.1 → cadquery script + execution.

Pipeline per IR:
  1. Validate (schema + semantic) via validator.validate
  2. Build declared operation trace
  3. Render each op via cadquery_backend to a list of statements
  4. Stitch statements into a runnable Python module
  5. Execute the module in a subprocess, capture stdout/stderr
  6. Determine per-op runtime status from the exception (if any)
  7. Build executed operation trace
  8. Emit adapter_report.json with all status flags
"""
from __future__ import annotations

import json
import sys
import textwrap
import traceback
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "validator"))
sys.path.insert(0, str(ROOT / "adaptor"))

from validator import validate  # noqa: E402
from adaptor.cadquery_backend import RENDERERS  # noqa: E402
from adaptor.trace_builder import build_declared_trace, build_executed_trace  # noqa: E402


SCRIPT_HEADER = textwrap.dedent("""\
    # AUTO-GENERATED by cad_ir/adaptor/adapter.py — DO NOT EDIT BY HAND.
    import sys, traceback
    try:
        import cadquery as cq
    except Exception as e:
        print("IMPORT_ERROR:", e)
        sys.exit(2)
""")


def _render_ir_to_script(ir: dict) -> tuple[str, list[dict], dict]:
    """Render an IR to a Python script (string).

    Returns (script_text, render_log, ctx_id_map).
    render_log entries: {op_id, op_type, status, error_type?, error_message?}
    """
    ctx_id: dict[str, str] = {}
    render_log: list[dict] = []
    statements: list[str] = []
    unsupported: list[str] = []

    # Import cq at top, with cwd-relative history path injection for the
    # ReconstructionEngine-style env.  We just rely on global cq here.
    statements.append(SCRIPT_HEADER.rstrip())

    # Wrap each op in try/except so a single bad op doesn't kill the whole script.
    for op in ir.get("operations", []):
        op_id = op.get("op_id")
        op_type = op.get("op_type")
        if not op_id or not op_type:
            render_log.append({"op_id": op_id, "op_type": op_type,
                                 "status": "error",
                                 "error_type": "render_error",
                                 "error_message": "missing op_id or op_type"})
            continue
        renderer = RENDERERS.get(op_type)
        if renderer is None:
            unsupported.append(op_id)
            render_log.append({"op_id": op_id, "op_type": op_type,
                                 "status": "skipped",
                                 "error_type": "unsupported_op",
                                 "error_message": f"unsupported op_type {op_type!r}"})
            statements.append(
                f"# SKIPPED: op {op_id} has unsupported op_type {op_type!r}")
            continue
        try:
            stmts = renderer(op, {}, ctx_id)
        except Exception as e:
            render_log.append({"op_id": op_id, "op_type": op_type,
                                 "status": "error",
                                 "error_type": "render_exception",
                                 "error_message": str(e)})
            statements.append(
                f"# RENDER ERROR for op {op_id}: {type(e).__name__}: {e}")
            continue
        # Wrap in try/except so individual op failures don't break the
        # whole script execution.
        statements.append(f"# --- op {op_id} ({op_type}) ---")
        statements.append(
            f"try:")
        for s in stmts:
            statements.append(f"    {s}")
        statements.append(
            f"except Exception as op_exc_{op_id.replace('-', '_')}:")
        statements.append(
            f'    print("OP_ERROR: op=" + {op_id!r} + " type=" + '
            f'{op_type!r} + " exc=" + repr(op_exc_{op_id.replace("-", "_")}))')
        statements.append(
            f"    raise")
        render_log.append({"op_id": op_id, "op_type": op_type,
                             "status": "rendered"})

    return ("\n".join(statements) + "\n",
            render_log,
            {"unsupported": unsupported, "ctx_id": ctx_id})


def _execute_script_subprocess(script_path: Path,
                                  step_path: Path) -> dict:
    """Execute the script in a subprocess, return execution outcome."""
    import subprocess
    script_path = Path(script_path).resolve()
    step_path = Path(step_path).resolve()
    try:
        proc = subprocess.run(
            [sys.executable, str(script_path)],
            capture_output=True, text=True, timeout=60,
            cwd=str(script_path.parent),
        )
        return {
            "return_code": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "step_exists": step_path.exists(),
        }
    except subprocess.TimeoutExpired:
        return {"return_code": -1, "stdout": "", "stderr": "timeout",
                "step_exists": step_path.exists()}
    except Exception as e:
        return {"return_code": -1, "stdout": "", "stderr": str(e),
                "step_exists": step_path.exists()}


def _extract_runtime_status(render_log: list[dict],
                              exec_outcome: dict) -> tuple[list[dict], str | None]:
    """Combine render + execute outcomes into per-op runtime_status list."""
    failed_at = None
    out = []
    stdout = exec_outcome.get("stdout", "")
    # OP_ERROR line format:  OP_ERROR: op='op_001' type='extrude' exc=...
    for r in render_log:
        op_id = r["op_id"]
        if r["status"] != "rendered":
            runtime_status = r["status"]
        else:
            # Check if OP_ERROR appears in stdout
            if f"op={op_id!r}" in stdout or f"op='{op_id}'" in stdout:
                runtime_status = "failed"
                if failed_at is None:
                    failed_at = op_id
            else:
                runtime_status = "success"
        out.append({"op_id": op_id, "op_type": r["op_type"],
                      "status": runtime_status})
    return out, failed_at


def adapt(ir: dict, out_dir: Path,
            sample_id: str | None = None) -> dict:
    """Top-level entry.  Writes generated_script.py + STEP + reports to out_dir.

    Returns the adapter_report dict.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    sample_id = sample_id or ir.get("sample_id", "unknown")
    report = {
        "sample_id": sample_id,
        "schema_check": "fail",
        "semantic_validation": "fail",
        "adapter_status": "fail",
        "script_syntax_status": "fail",
        "execution_status": "fail",
        "step_export_status": "fail",
        "unsupported_ops": [],
        "warnings": [],
    }

    # 1. Validate
    val = validate(ir)
    report["schema_check"] = val["schema_status"]
    report["semantic_validation"] = val["semantic_status"]
    if val["overall"] != "pass":
        report["warnings"].append(f"validation failed: {val}")
        (out_dir / "adapter_report.json").write_text(
            json.dumps(report, indent=2, ensure_ascii=False),
            encoding="utf-8")
        return report

    # 2. Declared trace
    declared_trace = build_declared_trace(ir)
    (out_dir / "declared_operation_trace.json").write_text(
        json.dumps(declared_trace, indent=2, ensure_ascii=False),
        encoding="utf-8")

    # 3. Render
    try:
        script_text, render_log, render_meta = _render_ir_to_script(ir)
        report["script_syntax_status"] = "pass"
        report["unsupported_ops"] = render_meta["unsupported"]
    except Exception as e:
        report["warnings"].append(f"render failed: {type(e).__name__}: {e}")
        report["script_syntax_status"] = "fail"
        script_text = "# render failed\n"
        render_log = []
        render_meta = {"unsupported": [], "ctx_id": {}}

    # Update export_step path to write into out_dir.
    # Use raw-string representation (r'...') so backslashes in Windows
    # paths are preserved instead of being interpreted as escape sequences.
    for op in ir.get("operations", []):
        if op.get("op_type") == "export_step":
            orig_path = op.get("params", {}).get("path", "out.step")
            new_path = str((out_dir / Path(orig_path).name).resolve())
            op["params"]["path"] = new_path
            script_text = script_text.replace(
                f"'{orig_path}'", f"r'{new_path}'")
    step_path = None
    for op in ir.get("operations", []):
        if op.get("op_type") == "export_step":
            step_path = Path(op["params"]["path"])
            break

    script_path = (out_dir / "generated_script.py").resolve()
    script_path.write_text(script_text, encoding="utf-8")

    # 4. Execute
    if step_path is None:
        step_path = out_dir / f"{sample_id}.step"
    exec_outcome = _execute_script_subprocess(script_path, step_path)
    (out_dir / "stdout.txt").write_text(exec_outcome.get("stdout", ""),
                                          encoding="utf-8")
    (out_dir / "stderr.txt").write_text(exec_outcome.get("stderr", ""),
                                          encoding="utf-8")

    report["execution_status"] = (
        "pass" if exec_outcome["return_code"] == 0 else "fail")
    report["step_export_status"] = (
        "pass" if exec_outcome["step_exists"] else "fail")
    report["adapter_status"] = (
        "success" if (report["script_syntax_status"] == "pass"
                       and report["execution_status"] == "pass"
                       and report["step_export_status"] == "pass")
        else "partial" if report["script_syntax_status"] == "pass" else "fail")
    report["return_code"] = exec_outcome["return_code"]

    # 5. Executed trace
    exec_results, failed_at = _extract_runtime_status(render_log, exec_outcome)
    executed_trace = build_executed_trace(ir, exec_results, failed_at)
    (out_dir / "executed_operation_trace.json").write_text(
        json.dumps(executed_trace, indent=2, ensure_ascii=False),
        encoding="utf-8")

    (out_dir / "adapter_report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False),
        encoding="utf-8")
    return report


def adapt_file(ir_path: Path, out_dir: Path) -> dict:
    """Convenience: load IR file then adapt."""
    ir = json.loads(ir_path.read_text(encoding="utf-8"))
    return adapt(ir, out_dir, sample_id=ir.get("sample_id"))